// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupplierPortal.Server.Data.Context;

#nullable disable

namespace SupplierPortal.Server.Migrations
{
    [DbContext(typeof(SupplierDbContext))]
    [Migration("20221013135615_AddedSupplierTable")]
    partial class AddedSupplierTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SupplierPortal.Shared.Models.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4a0a65be-0479-4727-8136-4794fbe2a9db"),
                            Company = "GetTech Limited",
                            Email = "gt@get.com",
                            Name = "XYZ"
                        },
                        new
                        {
                            Id = new Guid("6aaf0ae1-f37a-4062-a0e8-ee7baa76d3aa"),
                            Company = "Cleaning Limited",
                            Email = "clean@clean.com",
                            Name = "ABC"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
